# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171030_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 23, 49, 42, 287630), verbose_name='添加时间'),
        ),
    ]
