# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20171030_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 21, 52, 10, 241127), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 21, 52, 10, 240127), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 21, 52, 10, 239127), verbose_name='添加时间'),
        ),
    ]
